 
services: 
  db: 
    image: mysql:5.7 
    container_name: mysql_db 
    restart: unless-stopped  # Changed from 'always'
    environment: 
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: wordpress 
      MYSQL_USER: wpuser 
      MYSQL_PASSWORD: wppassword 
    ports: 
      - "3306:3306" 
    volumes: 
      - db_data:/var/lib/mysql 
 
  wordpress: 
    image: wordpress:latest 
    container_name: wordpress_app 
    restart: unless-stopped  # Changed from 'always'
    depends_on: 
      - db 
    environment: 
      WORDPRESS_DB_HOST: db:3306 
      WORDPRESS_DB_USER: wpuser 
      WORDPRESS_DB_PASSWORD: wppassword 
      WORDPRESS_DB_NAME: wordpress 
    ports: 
      - "8080:80" 
    volumes: 
      - wp_data:/var/www/html 
 
  wp-cli:
    image: wordpress:cli
    container_name: wp_cli
    depends_on:
      - wordpress
    volumes:
      - wp_data:/var/www/html
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
      WORDPRESS_DB_NAME: wordpress
    command: >
      sh -c 'sleep 10 && 
      wp core install --url=http://localhost:8080 --title="Test Site" --admin_user=admin --admin_password=password --admin_email=admin@example.com --skip-email &&
      wp plugin activate your-plugin &&
      wp test'
volumes: 
  db_data: 
  wp_data: 
